language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-26.0.0
    - android-26

# Enable travis container based infrastructure
sudo: false

before_script:
    - chmod +x gradlew

script:
    - ./gradlew clean assemble
